### ISSUE TITLE
Agregar interfaz básica para hits y filtros en Reguleque-React

### ISSUE THREAD

**Issue by agucova** [america-transparente/regulf-react#1]
Hay que empezar agregando alguno de los filtros básicos de la interfaz antigua, y por lo menos tarjetas básicas para los resultados (probablemente con solo un par de campos, para empezar).

**Comment by panquequelol** [comment]
Los primeros toques ya estan subidos, para hacer cosas como el modal voy usar [el componente Dialog de Headless UI](https://headlessui.com/react/dialog) una libreria de components sin estilar y ligera de la gende de Tailwind Labs

**Comment by panquequelol** [comment]
Todo
- [x] Scroll infinito
- [x] Tidy items (Corregir el formato de los hits)
- [x] Crear componente de modal (para mas info en hits, y mensaje de donacion) 
- [x] navbar responsive para telefonos
- [x] fix "mostrar mas" en filtros
- [x] Arreglar performance del debounce de la busqueda

menos prioridad:
- [x] crear componente de button
- [x] pasar letras de logo de america transparente a blanco
- [ ] boton para volver hacia arriba
- [x] crear searchbar personalizado
- [x] refactor scroll infinito, pasar component hit como prop

**Comment by panquequelol** [comment]
Listo!
