### ISSUE TITLE
Establecer esquema de colores y tipografías en Reguleque-React

### ISSUE THREAD

**Issue by agucova** [america-transparente/regulf-react#2]
Hay que describir un sistema básico de colores (la gradiente en la página actual es un buen inicio), y aplicarlo sobre los componentes por defecto de InstantSearch.js.

Asimismo, hay que crear un sistema tipográfico, donde creo que podemos innovar un poco.

**Comment by panquequelol** [comment]
Por ahora para ir construyendo los components y no hardcodearlos voy a agregar los dos colores de la gradiante del header de Reguleque al tema de Tailwind, despues podemos ver mas customizacion

```
primary: '#088d1b',
secondary: '#94ca02'
```

**Comment by panquequelol** [comment]
Los colors fueron definidos en la [libreria interna de React](https://github.com/america-transparente/ui), se pueden encontrar en la seccion de colors o en la configuracion de tailwind.
