### ISSUE TITLE
Agregar meta tags básicos a Reguleque-React

### ISSUE THREAD

**Issue by agucova** [america-transparente/regulf-react#3]
Para que la página tenga buen SEO y sea previsualizable desde redes sociales, hay que generar y agregar [meta tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name) adecuados a la nueva página. Un buen comienzo es [esta](https://metatags.io/) página.

Hay que crear un banner de Reguleque para esto. Ya que no tenemos el logo en buena definición, probablemente hay que replicarlo usando la tipografía y colores en la interfaz existente.

**Comment by panquequelol** [comment]
Por mientras hice esto, luego definimos bien que iria en los metatags

![Image](https://user-images.githubusercontent.com/65258503/189802306-3327dfe9-dcac-4ec8-ac0d-4063b85678e6.png)
Le cambie el metatags.io en los metatags

**Comment by agucova** [comment]
Ahí agregué una descripción más precisa. Con eso estaríamos por ahora.
